name: Deploy SAM (Option B)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  STACK_NAME: flask-portfolio-sam
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::820242946379:role/Github
          role-session-name: github-actions-sam-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Build
        run: sam build --no-use-container

      - name: SAM Deploy
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        run: |
          if [ -z "${FLASK_SECRET_KEY}" ]; then
            echo "Error: FLASK_SECRET_KEY GitHub secret is required and not set." >&2
            exit 1
          fi
          sam deploy \
            --stack-name "$STACK_NAME" \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides SecretKeyParam=${FLASK_SECRET_KEY} \
            --region "$AWS_REGION"

      - name: Show Outputs
        run: |
          aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs' --output table --region "$AWS_REGION"